// Curated emoji set for the chat emoji picker (composer + reactions). Kept as
// a small hand-picked list rather than pulling in a full emoji-data npm
// package — a few hundred common emojis covers real usage, and avoids adding
// a new dependency to the supply chain for something this self-contained.
export interface EmojiEntry {
  emoji: string;
  name: string;
  keywords: string;
}

export interface EmojiCategory {
  label: string;
  entries: EmojiEntry[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    label: 'Smileys & People',
    entries: [
      { emoji: '😀', name: 'grinning', keywords: 'happy smile' },
      { emoji: '😃', name: 'grinning big eyes', keywords: 'happy smile' },
      { emoji: '😄', name: 'smiling eyes', keywords: 'happy smile laugh' },
      { emoji: '😁', name: 'beaming', keywords: 'happy smile grin' },
      { emoji: '😆', name: 'laughing', keywords: 'happy lol haha' },
      { emoji: '😅', name: 'sweat smile', keywords: 'phew relief' },
      { emoji: '🤣', name: 'rofl', keywords: 'lol laughing haha' },
      { emoji: '😂', name: 'joy', keywords: 'lol laughing crying happy tears' },
      { emoji: '🙂', name: 'slightly smiling', keywords: 'smile ok' },
      { emoji: '🙃', name: 'upside down', keywords: 'silly sarcasm' },
      { emoji: '😉', name: 'wink', keywords: 'flirt' },
      { emoji: '😊', name: 'blush', keywords: 'happy smile shy' },
      { emoji: '😇', name: 'innocent', keywords: 'angel halo' },
      { emoji: '🥰', name: 'smiling hearts', keywords: 'love adore' },
      { emoji: '😍', name: 'heart eyes', keywords: 'love crush' },
      { emoji: '🤩', name: 'star struck', keywords: 'excited wow' },
      { emoji: '😘', name: 'kiss', keywords: 'love smooch' },
      { emoji: '😗', name: 'kissing', keywords: 'love' },
      { emoji: '😋', name: 'yum', keywords: 'delicious tasty food' },
      { emoji: '😛', name: 'tongue out', keywords: 'silly playful' },
      { emoji: '😜', name: 'winking tongue', keywords: 'silly playful' },
      { emoji: '🤪', name: 'zany', keywords: 'crazy silly' },
      { emoji: '😝', name: 'squinting tongue', keywords: 'silly' },
      { emoji: '🤑', name: 'money mouth', keywords: 'rich cash' },
      { emoji: '🤗', name: 'hugging', keywords: 'hug love' },
      { emoji: '🤭', name: 'hand over mouth', keywords: 'oops giggle' },
      { emoji: '🤫', name: 'shushing', keywords: 'quiet secret' },
      { emoji: '🤔', name: 'thinking', keywords: 'hmm consider' },
      { emoji: '🤨', name: 'raised eyebrow', keywords: 'skeptical suspicious' },
      { emoji: '😐', name: 'neutral', keywords: 'meh' },
      { emoji: '😑', name: 'expressionless', keywords: 'blank meh' },
      { emoji: '😶', name: 'no mouth', keywords: 'speechless' },
      { emoji: '😏', name: 'smirk', keywords: 'sly smug' },
      { emoji: '😒', name: 'unamused', keywords: 'annoyed meh' },
      { emoji: '🙄', name: 'eye roll', keywords: 'annoyed whatever' },
      { emoji: '😬', name: 'grimacing', keywords: 'awkward yikes' },
      { emoji: '🤥', name: 'lying', keywords: 'pinocchio' },
      { emoji: '😌', name: 'relieved', keywords: 'calm content' },
      { emoji: '😔', name: 'pensive', keywords: 'sad thoughtful' },
      { emoji: '😪', name: 'sleepy', keywords: 'tired' },
      { emoji: '🤤', name: 'drooling', keywords: 'hungry' },
      { emoji: '😴', name: 'sleeping', keywords: 'zzz tired' },
      { emoji: '😷', name: 'mask', keywords: 'sick ill' },
      { emoji: '🤒', name: 'thermometer', keywords: 'sick fever' },
      { emoji: '🤕', name: 'bandage', keywords: 'hurt injured' },
      { emoji: '🤢', name: 'nauseated', keywords: 'sick gross' },
      { emoji: '🤮', name: 'vomiting', keywords: 'sick gross' },
      { emoji: '🥵', name: 'hot', keywords: 'heat sweating' },
      { emoji: '🥶', name: 'cold', keywords: 'freezing' },
      { emoji: '😵', name: 'dizzy', keywords: 'confused knocked out' },
      { emoji: '🤯', name: 'exploding head', keywords: 'mind blown shocked' },
      { emoji: '🥳', name: 'partying', keywords: 'celebrate party' },
      { emoji: '😎', name: 'sunglasses', keywords: 'cool' },
      { emoji: '🤓', name: 'nerd', keywords: 'geek glasses' },
      { emoji: '🧐', name: 'monocle', keywords: 'inspecting curious' },
      { emoji: '😕', name: 'confused', keywords: 'unsure' },
      { emoji: '😟', name: 'worried', keywords: 'concerned' },
      { emoji: '🙁', name: 'slight frown', keywords: 'sad' },
      { emoji: '😮', name: 'open mouth', keywords: 'surprised wow' },
      { emoji: '😯', name: 'hushed', keywords: 'surprised' },
      { emoji: '😲', name: 'astonished', keywords: 'shocked wow' },
      { emoji: '😳', name: 'flushed', keywords: 'embarrassed blush' },
      { emoji: '🥺', name: 'pleading', keywords: 'puppy eyes please' },
      { emoji: '😦', name: 'frowning open mouth', keywords: 'shocked' },
      { emoji: '😧', name: 'anguished', keywords: 'shocked' },
      { emoji: '😨', name: 'fearful', keywords: 'scared' },
      { emoji: '😰', name: 'anxious sweat', keywords: 'nervous worried' },
      { emoji: '😥', name: 'sad relieved', keywords: 'disappointed' },
      { emoji: '😢', name: 'crying', keywords: 'sad tears' },
      { emoji: '😭', name: 'sobbing', keywords: 'crying sad loud' },
      { emoji: '😱', name: 'screaming fear', keywords: 'shocked scared' },
      { emoji: '😖', name: 'confounded', keywords: 'frustrated' },
      { emoji: '😣', name: 'persevering', keywords: 'struggling' },
      { emoji: '😞', name: 'disappointed', keywords: 'sad' },
      { emoji: '😓', name: 'downcast sweat', keywords: 'stressed tired' },
      { emoji: '😩', name: 'weary', keywords: 'tired exhausted' },
      { emoji: '😫', name: 'tired', keywords: 'exhausted' },
      { emoji: '🥱', name: 'yawning', keywords: 'tired bored' },
      { emoji: '😤', name: 'triumphant', keywords: 'proud frustrated' },
      { emoji: '😡', name: 'pouting angry', keywords: 'mad furious' },
      { emoji: '😠', name: 'angry', keywords: 'mad' },
      { emoji: '🤬', name: 'cursing', keywords: 'angry swearing' },
      { emoji: '👍', name: 'thumbs up', keywords: 'yes agree good' },
      { emoji: '👎', name: 'thumbs down', keywords: 'no disagree bad' },
      { emoji: '👏', name: 'clapping', keywords: 'applause bravo' },
      { emoji: '🙌', name: 'raised hands', keywords: 'celebrate praise' },
      { emoji: '🙏', name: 'folded hands', keywords: 'please thanks pray' },
      { emoji: '👋', name: 'waving', keywords: 'hello bye' },
      { emoji: '🤝', name: 'handshake', keywords: 'deal agreement' },
      { emoji: '💪', name: 'flexed biceps', keywords: 'strong muscle' },
      { emoji: '✌️', name: 'victory', keywords: 'peace' },
      { emoji: '🤞', name: 'crossed fingers', keywords: 'hope luck' },
      { emoji: '👌', name: 'ok hand', keywords: 'okay perfect' },
      { emoji: '👀', name: 'eyes', keywords: 'look watching' },
      { emoji: '🧠', name: 'brain', keywords: 'smart think idea' },
    ],
  },
  {
    label: 'Gestures & Hearts',
    entries: [
      { emoji: '❤️', name: 'red heart', keywords: 'love' },
      { emoji: '🧡', name: 'orange heart', keywords: 'love' },
      { emoji: '💛', name: 'yellow heart', keywords: 'love' },
      { emoji: '💚', name: 'green heart', keywords: 'love' },
      { emoji: '💙', name: 'blue heart', keywords: 'love' },
      { emoji: '💜', name: 'purple heart', keywords: 'love' },
      { emoji: '🖤', name: 'black heart', keywords: 'love' },
      { emoji: '🤍', name: 'white heart', keywords: 'love' },
      { emoji: '💔', name: 'broken heart', keywords: 'sad breakup' },
      { emoji: '❣️', name: 'heart exclamation', keywords: 'love' },
      { emoji: '💕', name: 'two hearts', keywords: 'love' },
      { emoji: '💖', name: 'sparkling heart', keywords: 'love' },
      { emoji: '💯', name: 'hundred', keywords: 'perfect score' },
      { emoji: '✅', name: 'check mark', keywords: 'done yes correct' },
      { emoji: '❌', name: 'cross mark', keywords: 'no wrong' },
      { emoji: '❓', name: 'question mark', keywords: 'confused unsure' },
      { emoji: '❗', name: 'exclamation mark', keywords: 'important warning' },
      { emoji: '⭐', name: 'star', keywords: 'favorite' },
      { emoji: '🌟', name: 'glowing star', keywords: 'shine amazing' },
      { emoji: '✨', name: 'sparkles', keywords: 'shiny magic' },
      { emoji: '🔥', name: 'fire', keywords: 'lit hot great' },
      { emoji: '🎉', name: 'party popper', keywords: 'celebrate' },
      { emoji: '🎊', name: 'confetti ball', keywords: 'celebrate' },
      { emoji: '🎁', name: 'gift', keywords: 'present' },
      { emoji: '🏆', name: 'trophy', keywords: 'win award' },
      { emoji: '🥇', name: 'gold medal', keywords: 'first place win' },
    ],
  },
  {
    label: 'Objects & Work',
    entries: [
      { emoji: '💻', name: 'laptop', keywords: 'computer work' },
      { emoji: '🖥️', name: 'desktop', keywords: 'computer work' },
      { emoji: '📱', name: 'phone', keywords: 'mobile' },
      { emoji: '⌨️', name: 'keyboard', keywords: 'typing' },
      { emoji: '🖱️', name: 'mouse', keywords: 'computer' },
      { emoji: '📷', name: 'camera', keywords: 'photo' },
      { emoji: '🎥', name: 'video camera', keywords: 'movie recording' },
      { emoji: '🎤', name: 'microphone', keywords: 'voice sing' },
      { emoji: '📧', name: 'email', keywords: 'mail message' },
      { emoji: '📨', name: 'incoming envelope', keywords: 'mail message' },
      { emoji: '📁', name: 'folder', keywords: 'files' },
      { emoji: '📎', name: 'paperclip', keywords: 'attachment' },
      { emoji: '📌', name: 'pushpin', keywords: 'pin important' },
      { emoji: '📅', name: 'calendar', keywords: 'date schedule' },
      { emoji: '⏰', name: 'alarm clock', keywords: 'time reminder' },
      { emoji: '⏳', name: 'hourglass', keywords: 'time waiting' },
      { emoji: '📊', name: 'bar chart', keywords: 'data stats' },
      { emoji: '📈', name: 'chart up', keywords: 'growth increase' },
      { emoji: '📉', name: 'chart down', keywords: 'decrease decline' },
      { emoji: '📝', name: 'memo', keywords: 'notes write' },
      { emoji: '✏️', name: 'pencil', keywords: 'write edit' },
      { emoji: '🖊️', name: 'pen', keywords: 'write' },
      { emoji: '📄', name: 'document', keywords: 'file page' },
      { emoji: '📦', name: 'package', keywords: 'box shipping' },
      { emoji: '🔗', name: 'link', keywords: 'url chain' },
      { emoji: '🔒', name: 'locked', keywords: 'secure private' },
      { emoji: '🔓', name: 'unlocked', keywords: 'open' },
      { emoji: '🔑', name: 'key', keywords: 'access password' },
      { emoji: '💡', name: 'lightbulb', keywords: 'idea' },
      { emoji: '🔍', name: 'magnifying glass', keywords: 'search find' },
      { emoji: '⚙️', name: 'gear', keywords: 'settings config' },
      { emoji: '🚀', name: 'rocket', keywords: 'launch ship deploy' },
      { emoji: '🐛', name: 'bug', keywords: 'error issue' },
      { emoji: '🛠️', name: 'tools', keywords: 'fix build' },
    ],
  },
  {
    label: 'Food & Drink',
    entries: [
      { emoji: '☕', name: 'coffee', keywords: 'drink cafe' },
      { emoji: '🍵', name: 'tea', keywords: 'drink' },
      { emoji: '🍕', name: 'pizza', keywords: 'food' },
      { emoji: '🍔', name: 'burger', keywords: 'food' },
      { emoji: '🍟', name: 'fries', keywords: 'food' },
      { emoji: '🌮', name: 'taco', keywords: 'food' },
      { emoji: '🍰', name: 'cake', keywords: 'dessert birthday' },
      { emoji: '🍩', name: 'donut', keywords: 'dessert' },
      { emoji: '🍎', name: 'apple', keywords: 'fruit' },
      { emoji: '🍺', name: 'beer', keywords: 'drink' },
      { emoji: '🥂', name: 'cheers', keywords: 'celebrate drink toast' },
    ],
  },
  {
    label: 'Travel & Places',
    entries: [
      { emoji: '🚗', name: 'car', keywords: 'travel drive' },
      { emoji: '✈️', name: 'airplane', keywords: 'travel flight' },
      { emoji: '🚆', name: 'train', keywords: 'travel' },
      { emoji: '🏠', name: 'house', keywords: 'home' },
      { emoji: '🏢', name: 'office building', keywords: 'work' },
      { emoji: '🌍', name: 'globe', keywords: 'world' },
      { emoji: '🌙', name: 'moon', keywords: 'night' },
      { emoji: '☀️', name: 'sun', keywords: 'day sunny' },
      { emoji: '🌧️', name: 'rain', keywords: 'weather' },
    ],
  },
];

export const QUICK_REACTION_EMOJIS = ['👍', '❤️', '😂', '🔥', '👏', '🎉'];

export const ALL_EMOJIS: EmojiEntry[] = EMOJI_CATEGORIES.flatMap((c) => c.entries);
