const v1 = 'api/v1';

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN:          `${v1}/auth/login`,
    REGISTER:       `${v1}/auth/register`,
    VERIFY_OTP:     (id: string | number) => `${v1}/auth/verify/${id}`,
    RESEND_OTP:     (id: string | number) => `${v1}/auth/resendOTP/${id}`,
    FORGOT_PASSWORD:`${v1}/auth/forgot`,
    RESET_PASSWORD: (id: string | number) => `${v1}/auth/reset/${id}`,
    ME:             `${v1}/auth/me`,
    REFRESH:        `${v1}/auth/refresh`,
    LOGOUT:         `${v1}/auth/logout`,
  },
  TEAM: {
    LIST:        `${v1}/team`,
    CREATE:      `${v1}/team`,
    DELETE_MANY: `${v1}/team`,
    DETAIL:      (id: string | number) => `${v1}/team/${id}`,
    UPDATE:      (id: string | number) => `${v1}/team/${id}`,
    DELETE:      (id: string | number) => `${v1}/team/${id}`,
    MEMBERS:     (id: string | number) => `${v1}/team/${id}/members`,
    MEMBER:      (id: string | number, userId: string) => `${v1}/team/${id}/members/${userId}`,
  },
  BUSINESS_UNIT: {
    LIST:        `${v1}/business-units`,
    CREATE:      `${v1}/business-units`,
    DETAIL:      (id: string | number) => `${v1}/business-units/${id}`,
    UPDATE:      (id: string | number) => `${v1}/business-units/${id}`,
    DELETE:      (id: string | number) => `${v1}/business-units/${id}`,
    BULK_DELETE: `${v1}/business-units/bulk-delete`,
  },
  DEPARTMENT: {
    LIST:        `${v1}/department`,
    CREATE:      `${v1}/department`,
    DETAIL:      (id: string | number) => `${v1}/department/${id}`,
    UPDATE:      (id: string | number) => `${v1}/department/${id}`,
    DELETE:      (id: string | number) => `${v1}/department/${id}`,
    BULK_DELETE: `${v1}/department/bulk-delete`,
    BULK_UPDATE_BUSINESS_UNIT: `${v1}/department/bulk-update-business-unit`,
    BULK_UPDATE_BUSINESS_FUNCTION: `${v1}/department/bulk-update-business-function`,
    DIVISIONS:   (id: string | number) => `${v1}/department/${id}/divisions`,
  },
  DIVISION: {
    LIST:        `${v1}/divisions`,
    DETAIL:      (id: string | number) => `${v1}/divisions/${id}`,
    UPDATE:      (id: string | number) => `${v1}/divisions/${id}`,
    DELETE:      (id: string | number) => `${v1}/divisions/${id}`,
    BULK_DELETE: `${v1}/divisions/bulk-delete`,
    BULK_ASSIGN_DEPARTMENTS: `${v1}/divisions/bulk-assign-departments`,
  },
  DESIGNATION: {
    LIST:        `${v1}/designations`,
    CREATE:      `${v1}/designations`,
    DETAIL:      (id: string | number) => `${v1}/designations/${id}`,
    UPDATE:      (id: string | number) => `${v1}/designations/${id}`,
    DELETE:      (id: string | number) => `${v1}/designations/${id}`,
    BULK_DELETE: `${v1}/designations/bulk-delete`,
  },
  GRADE: {
    LIST:   `${v1}/grades`,
    CREATE: `${v1}/grades`,
    DETAIL: (id: string | number) => `${v1}/grades/${id}`,
    UPDATE: (id: string | number) => `${v1}/grades/${id}`,
    DELETE: (id: string | number) => `${v1}/grades/${id}`,
  },
  ROLE: {
    LIST: `${v1}/user/roles`,
  },
  INVITE: {
    LIST:        `${v1}/invite`,
    CREATE:      `${v1}/invite`,
    DELETE_MANY: `${v1}/invite`,
    PREVIEW:     (token: string) => `${v1}/invite/token/${token}/preview`,
    REDEEM:      `${v1}/invite/redeem`,
    DETAIL:      (id: string | number) => `${v1}/invite/${id}`,
    UPDATE:      (id: string | number) => `${v1}/invite/${id}`,
    DELETE:      (id: string | number) => `${v1}/invite/${id}`,
    ACCEPT:      (id: string | number) => `${v1}/invite/${id}/accept`,
  },
  USER: {
    ME_UPDATE:   `${v1}/user/me`,
    LIST:        `${v1}/user`,
    CREATE:      `${v1}/user`,
    UPDATE_MANY: `${v1}/user`,
    DELETE_MANY: `${v1}/user`,
    DETAIL:      (id: string | number) => `${v1}/user/${id}`,
    UPDATE:      (id: string | number) => `${v1}/user/${id}`,
    DELETE:       (id: string | number) => `${v1}/user/${id}`,
    BULK_DELETE:  `${v1}/user/bulk-delete`,

    ROLE_CHANGE: (id: string | number) => `${v1}/user/${id}/role`,
    EMPLOYEE_ID_PREVIEW: (departmentId: string | number) => `${v1}/user/employee-id/preview?department_id=${departmentId}`,

    EMPLOYEE_ID_CHANGE: (id: string | number) => `${v1}/user/${id}/employee-id`,

    AVATAR_UPLOAD: (id: string | number) => `${v1}/user/${id}/avatar`,

    MY_PUBLIC_KEY:   `${v1}/user/me/public-key`,
    PUBLIC_KEY:      (id: string | number) => `${v1}/user/${id}/public-key`,
  },
  EMPLOYEE_LIFECYCLE: {

    SET_STAGE: `${v1}/employee-lifecycle/set-stage`,

    MOVE_TO_PROBATION:     (userId: string | number) => `${v1}/employee-lifecycle/${userId}/move-to-probation`,
    ENTER_NOTICE_PERIOD:   (userId: string | number) => `${v1}/employee-lifecycle/${userId}/enter-notice-period`,
    MOVE_TO_EXIT_CLEARANCE:(userId: string | number) => `${v1}/employee-lifecycle/${userId}/move-to-exit-clearance`,
    ARCHIVE:               (userId: string | number) => `${v1}/employee-lifecycle/${userId}/archive`,

    REQUEST_CONFIRM_EMPLOYEE:    (userId: string | number) => `${v1}/employee-lifecycle/${userId}/request-confirm-employee`,
    REQUEST_EXTEND_PROBATION:    (userId: string | number) => `${v1}/employee-lifecycle/${userId}/request-extend-probation`,
    REQUEST_TERMINATE_PROBATION: (userId: string | number) => `${v1}/employee-lifecycle/${userId}/request-terminate-probation`,
    REQUEST_ARCHIVE:              (userId: string | number) => `${v1}/employee-lifecycle/${userId}/request-archive`,
  },
  PROJECT: {
    LIST:      `${v1}/project`,
    EMPLOYEE_LIST: `${v1}/project/my`,
    CREATE:    `${v1}/project`,
    SAVED:     `${v1}/project/saved`,
    DASHBOARD: `${v1}/project/dashboard`,
    DETAIL: (id: string | number) => `${v1}/project/${id}`,
    UPDATE: (id: string | number) => `${v1}/project/${id}`,
    DELETE: (id: string | number) => `${v1}/project/${id}`,
    RESTORE:   (id: string | number) => `${v1}/project/${id}/restore`,
    SAVE:      (id: string | number) => `${v1}/project/${id}/save`,
    UNSAVE:    (id: string | number) => `${v1}/project/${id}/save`,
    BUDGET:    (id: string | number) => `${v1}/project/${id}/budget`,
    EXTENSION: (id: string | number) => `${v1}/project/${id}/extension`,
    EXTENSION_REVIEW: (id: string | number, requestId: string) => `${v1}/project/${id}/extension/${requestId}`,
    RESOURCES: (id: string | number) => `${v1}/project/${id}/resources`,
    CLIENTS_LOOKUP: `${v1}/project/clients-lookup`,
  },

  PERFORMANCE_REVIEW: {
    LIST:     `${v1}/performance-reviews`,
    CREATE:   `${v1}/performance-reviews`,
    DETAIL:   (id: string) => `${v1}/performance-reviews/${id}`,
    EVIDENCE: (id: string) => `${v1}/performance-reviews/${id}/evidence`,
    UPDATE:   (id: string) => `${v1}/performance-reviews/${id}`,
    DELETE:   (id: string) => `${v1}/performance-reviews/${id}`,
    ADD_MANAGER_EVIDENCE: (id: string) => `${v1}/performance-reviews/${id}/evidence`,
    DELETE_MANAGER_EVIDENCE: (id: string, evidenceId: string) => `${v1}/performance-reviews/${id}/evidence/${evidenceId}`,

    RECORD_DECISION: (id: string) => `${v1}/performance-reviews/${id}/decision`,
  },
  REVIEW_PERIOD: {
    LIST:   `${v1}/review-periods`,
    CREATE: `${v1}/review-periods`,
    UPDATE: (id: string) => `${v1}/review-periods/${id}`,
  },
  TRACKING_LINKS: {
    LIST:   (projectId: string) => `${v1}/project/${projectId}/tracking-links`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/tracking-links`,
    DELETE: (projectId: string, linkId: string) => `${v1}/project/${projectId}/tracking-links/${linkId}`,
  },
  WEEKLY_UPDATES: {
    LIST:   (projectId: string) => `${v1}/project/${projectId}/weekly-updates`,
    LATEST: (projectId: string) => `${v1}/project/${projectId}/weekly-updates/latest`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/weekly-updates`,
    DELETE: (projectId: string, updateId: string) => `${v1}/project/${projectId}/weekly-updates/${updateId}`,
  },
  PROJECT_DISCUSSIONS: {
    LIST:   (projectId: string) => `${v1}/project/${projectId}/discussions`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/discussions`,
    DELETE: (projectId: string, discussionId: string) => `${v1}/project/${projectId}/discussions/${discussionId}`,
  },
  COMMUNICATION_TIMELINE: {
    GET: (projectId: string) => `${v1}/project/${projectId}/communication-timeline`,
  },
  PROJECT_DOCUMENTS: {
    TYPES:  (projectId: string) => `${v1}/project/${projectId}/documents/types`,
    LIST:   (projectId: string) => `${v1}/project/${projectId}/documents`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/documents`,
    DELETE: (projectId: string, docId: string) => `${v1}/project/${projectId}/documents/${docId}`,
  },
  PROJECT_TIMELINE: {
    LIST: (projectId: string) => `${v1}/project/${projectId}/timeline`,
  },
  TIMESHEET: {
    WEEKLY:          `${v1}/timesheet/weekly`,
    RANGE:           `${v1}/timesheet/range`,
    RECENT_ACTIVITY: `${v1}/timesheet/recent-activity`,
    REQUESTS:        `${v1}/timesheet/requests`,
    MY_REQUESTS:     `${v1}/timesheet/my-requests`,
    POLICIES:        `${v1}/timesheet/time-off/policies`,
    REQUEST_TIME_OFF:`${v1}/timesheet/time-off/request`,
    CREATE_ENTRY:    `${v1}/timesheet/entry`,
    CLOCK_IN:        `${v1}/timesheet/clock-in`,
    CLOCK_OUT:       `${v1}/timesheet/clock-out`,
    FORCE_CHECKOUT:  `${v1}/timesheet/force-checkout`,
    TODAY:           `${v1}/timesheet/today`,
    COMPLIANCE_STATUS: `${v1}/timesheet/compliance-status`,
    DETAIL:          (id: string | number) => `${v1}/timesheet/entry/${id}`,
    UPDATE:          (id: string | number) => `${v1}/timesheet/entry/${id}`,
    DELETE:          (id: string | number) => `${v1}/timesheet/entry/${id}`,
    REQUEST_EDIT:    (id: string | number) => `${v1}/timesheet/entry/${id}/request`,
    APPROVE_EDIT:    (id: string | number) => `${v1}/timesheet/edit-request/${id}/approve`,
    REJECT_EDIT:     (id: string | number) => `${v1}/timesheet/edit-request/${id}/reject`,
    APPROVE_TIMEOFF: (id: string | number) => `${v1}/timesheet/time-off/${id}/approve`,
    REJECT_TIMEOFF:  (id: string | number) => `${v1}/timesheet/time-off/${id}/reject`,
    DELETE_TIMEOFF:  (id: string | number) => `${v1}/timesheet/time-off/${id}`,
  },
  SETTINGS: {
    ME:            `${v1}/settings/me`,
    PREFERENCES:   `${v1}/settings/preferences`,
    PASSWORD:      `${v1}/settings/password`,
    SYSTEM:        `${v1}/settings/system`,
    SYSTEM_PUBLIC: `${v1}/settings/system/public`,
    BUSINESS_UNIT_REPORT_EMAIL:      `${v1}/settings/business-unit-report-email`,
    BUSINESS_UNIT_REPORT_EMAIL_ITEM: (businessUnitId: string) => `${v1}/settings/business-unit-report-email/${businessUnitId}`,
  },
  STARRED: {
    QUERIES:    `${v1}/starred/queries`,
    STAR_ITEM:  (item_type: string, id: string | number) => `${v1}/starred/${item_type}/${id}`,
    UNSTAR_ITEM:(item_type: string, id: string | number) => `${v1}/starred/${item_type}/${id}`,
  },
  NOTIFICATION: {
    LIST:      `${v1}/notification`,
    MARK_READ: (id: string | number) => `${v1}/notification/${id}/read`,
    READ_ALL:  `${v1}/notification/read-all`,
    DELETE:    (id: string | number) => `${v1}/notification/${id}`,
  },
  TICKET: {
    LIST:        `${v1}/ticket`,
    CREATE:      `${v1}/ticket`,
    STATS:       `${v1}/ticket/stats`,
    DETAIL:      (id: string | number) => `${v1}/ticket/${id}`,
    UPDATE:      (id: string | number) => `${v1}/ticket/${id}`,
    DELETE:      (id: string | number) => `${v1}/ticket/${id}`,
    ATTACHMENTS: (id: string | number) => `${v1}/ticket/${id}/attachments`,
    REPLIES:     (id: string | number) => `${v1}/ticket/${id}/replies`,
    APPROVALS:   (id: string | number) => `${v1}/ticket/${id}/approvals`,
    TIMELINE:    (id: string | number) => `${v1}/ticket/${id}/timeline`,
  },
  TICKET_CATEGORY: {
    LIST:   `${v1}/ticket-categories`,
    CREATE: `${v1}/ticket-categories`,
    DETAIL: (id: string | number) => `${v1}/ticket-categories/${id}`,
    UPDATE: (id: string | number) => `${v1}/ticket-categories/${id}`,
    ACTIVE: (id: string | number) => `${v1}/ticket-categories/${id}/active`,
  },
  TICKET_TYPE: {
    LIST:      `${v1}/ticket-types`,
    CREATE:    `${v1}/ticket-types`,
    DETAIL:    (id: string | number) => `${v1}/ticket-types/${id}`,
    UPDATE:    (id: string | number) => `${v1}/ticket-types/${id}`,
    ACTIVE:    (id: string | number) => `${v1}/ticket-types/${id}/active`,
    ASSIGNEES: (id: string | number) => `${v1}/ticket-types/${id}/assignees`,
  },
  MARKETING: {
    DEALS:              `${v1}/marketing/deals`,
    SALARY_BUILDER:     `${v1}/marketing/salary-builder`,
    SALARY_HISTORY:     `${v1}/marketing/salary-history`,
    PUBLISH_SALARY:     (userId: string, period: string) => `${v1}/marketing/salary-builder/${userId}/${period}/publish`,
    WON_DEALS:          `${v1}/marketing/won-deals`,
    UPWORK:             `${v1}/marketing/upwork`,
    UPWORK_ITEM:        (id: string) => `${v1}/marketing/upwork/${id}`,
    LINKEDIN:           `${v1}/marketing/linkedin`,
    LINKEDIN_ITEM:      (id: string) => `${v1}/marketing/linkedin/${id}`,
    EMAIL_LEADS:        `${v1}/marketing/email-leads`,
    EMAIL_LEADS_ITEM:   (id: string) => `${v1}/marketing/email-leads/${id}`,
    LINKEDIN_ACTIVITY:  `${v1}/marketing/linkedin-activity`,
    LEAD_ACTIVITIES:    `${v1}/marketing/lead-activities`,
    DEPOSITS:           `${v1}/marketing/deposits`,
    DEPOSIT_ITEM:       (id: string) => `${v1}/marketing/deposits/${id}`,
    DEPOSIT_TARGET:     `${v1}/marketing/deposit-target`,
    TARGETS:            `${v1}/marketing/targets`,
    MY_REPORT:          `${v1}/marketing/my-report`,
    MY_SALARIES:        `${v1}/marketing/my-salaries`,
    MEMBERS:            `${v1}/marketing/members`,
  },
  ASSET: {
    LIST:        `${v1}/asset`,
    CREATE:      `${v1}/asset`,
    CATEGORIES:  `${v1}/asset/categories`,
    LOCATIONS:   `${v1}/asset/locations`,
    VENDORS:     `${v1}/asset/vendors`,
    DETAIL:      (id: string | number) => `${v1}/asset/${id}`,
    UPDATE:      (id: string | number) => `${v1}/asset/${id}`,
    DELETE:      (id: string | number) => `${v1}/asset/${id}`,
    ASSIGN:      (id: string | number) => `${v1}/asset/${id}/assign`,
    RETURN:      (id: string | number) => `${v1}/asset/${id}/return`,
    MAINTENANCE: (id: string | number) => `${v1}/asset/${id}/maintenance`,
    REQUESTS:         `${v1}/asset/requests`,
    REQUEST_APPROVE:  (id: string | number) => `${v1}/asset/requests/${id}/approve`,
    REQUEST_REJECT:   (id: string | number) => `${v1}/asset/requests/${id}/reject`,
    DISPOSALS:        `${v1}/asset/disposals`,
    REPORT_DEPRECIATION: `${v1}/asset/reports/depreciation`,
    REPORT_INVENTORY:    `${v1}/asset/reports/inventory`,
    RECEIVE:      (id: string | number) => `${v1}/asset/${id}/receive`,
    CUSTODY_EVENTS: (id: string | number) => `${v1}/asset/${id}/custody-events`,
    ALL_CUSTODY_EVENTS: `${v1}/asset/custody-events`,
    CUSTODY_EVENT_ATTACHMENTS: (id: string | number, eventId: string) => `${v1}/asset/${id}/custody-events/${eventId}/attachments`,
    CUSTODY_EVENT_ATTACHMENT_DELETE: (id: string | number, eventId: string, attachmentId: string) => `${v1}/asset/${id}/custody-events/${eventId}/attachments/${attachmentId}`,
    REPLACEMENTS: `${v1}/asset/replacements`,
  },
  PERFORMANCE: {
    DAILY_REPORTS: `${v1}/performance/daily-report`,
    DAILY_REPORT:  (id: string | number) => `${v1}/performance/daily-report/${id}`,
    SCORES:        `${v1}/performance/score`,
    SCORE_BY_EMP:  (empId: string) => `${v1}/performance/score/${empId}`,
    DELETE_SCORE:  (id: string | number) => `${v1}/performance/score/${id}`,
    BONUS_CONFIG:  `${v1}/performance/bonus-config`,
    BONUS:         `${v1}/performance/bonus`,
    CALC_BONUS:    `${v1}/performance/bonus/calculate`,
    APPROVE_BONUS: (id: string | number) => `${v1}/performance/bonus/${id}/approve`,
    PAY_BONUS:     (id: string | number) => `${v1}/performance/bonus/${id}/pay`,
  },

  TASK: {
    LIST:   (projectId: string) => `${v1}/project/${projectId}/tasks`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/tasks`,
    DETAIL: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}`,
    UPDATE: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}`,
    DELETE: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}`,
    ARCHIVE:      (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/archive`,
    UNARCHIVE:    (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/unarchive`,
    DEPENDENCIES: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/dependencies`,
  },
  TASK_COMMENTS: {
    LIST:   (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/comments`,
    CREATE: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/comments`,
    DELETE: (projectId: string, taskId: string, commentId: string) => `${v1}/project/${projectId}/tasks/${taskId}/comments/${commentId}`,
  },
  TASK_ATTACHMENTS: {
    LIST:   (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/attachments`,
    CREATE: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/attachments`,
    DELETE: (projectId: string, taskId: string, attachmentId: string) => `${v1}/project/${projectId}/tasks/${taskId}/attachments/${attachmentId}`,
  },

  SUB_TASKS: (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/sub-tasks`,
  TIME_LOGS:  (projectId: string, taskId: string) => `${v1}/project/${projectId}/tasks/${taskId}/time-logs`,

  MILESTONE: {
    LIST:      (projectId: string) => `${v1}/project/${projectId}/milestones`,
    CREATE:    (projectId: string) => `${v1}/project/${projectId}/milestones`,
    DETAIL:    (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}`,
    UPDATE:    (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}`,
    DELETE:    (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}`,
    ARCHIVE:   (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}/archive`,
    UNARCHIVE: (projectId: string, milestoneId: string) => `${v1}/project/${projectId}/milestones/${milestoneId}/unarchive`,
    REORDER:   (projectId: string) => `${v1}/project/${projectId}/milestones/reorder`,
  },

  DEVOPS_ACCESS: {
    GET:    (projectId: string) => `${v1}/project/${projectId}/devops-access`,
    UPDATE: (projectId: string) => `${v1}/project/${projectId}/devops-access`,
  },
  DEPENDENCIES: {
    LIST:   (projectId: string) => `${v1}/project/${projectId}/dependencies`,
    CREATE: (projectId: string) => `${v1}/project/${projectId}/dependencies`,
    UPDATE: (projectId: string, dependencyId: string) => `${v1}/project/${projectId}/dependencies/${dependencyId}`,
    DELETE: (projectId: string, dependencyId: string) => `${v1}/project/${projectId}/dependencies/${dependencyId}`,
  },
  HR_PROFILE: {
    DESIGNATIONS:  `${v1}/hr-profile/designations`,
    GET:           (userId: string) => `${v1}/hr-profile/${userId}`,
    UPDATE:        (userId: string) => `${v1}/hr-profile/${userId}`,
    FULL_RECORD:   (userId: string) => `${v1}/hr-profile/${userId}/full`,
  },
  REPORTING_STRUCTURE: {
    GET: (userId: string) => `${v1}/user/${userId}/reporting-structure`,
  },
  LIFECYCLE_APPROVALS: {
    LIST: `${v1}/lifecycle-approvals`,
  },
  ACTIVITY_LOG: {
    LIST: `${v1}/activity-log`,
  },
  EMPLOYEE_NOTES: {
    LIST:   (userId: string) => `${v1}/employee-notes/${userId}`,
    CREATE: (userId: string) => `${v1}/employee-notes/${userId}`,
    UPDATE: (userId: string, noteId: string) => `${v1}/employee-notes/${userId}/${noteId}`,
    DELETE: (userId: string, noteId: string) => `${v1}/employee-notes/${userId}/${noteId}`,
  },
  STORAGE: {
    UPLOAD: `${v1}/storage/upload`,
  },
  EMPLOYEE_DOC: {
    TYPES:   `${v1}/employee-doc/types`,
    LIST:    (userId: string) => `${v1}/employee-doc/${userId}`,
    CREATE:  (userId: string) => `${v1}/employee-doc/${userId}`,

    UPLOAD:  (userId: string) => `${v1}/employee-doc/${userId}/upload`,
    UPDATE:  (userId: string, docId: string) => `${v1}/employee-doc/${userId}/${docId}`,
    DELETE:  (userId: string, docId: string) => `${v1}/employee-doc/${userId}/${docId}`,
  },
  REQUISITION: {
    META:          `${v1}/requisition/meta`,
    STATS:         `${v1}/requisition/stats`,
    LIST:          `${v1}/requisition`,
    CREATE:        `${v1}/requisition`,
    DETAIL:        (id: string) => `${v1}/requisition/${id}`,
    UPDATE:        (id: string) => `${v1}/requisition/${id}`,
    SUBMIT:        (id: string) => `${v1}/requisition/${id}/submit`,
    APPROVE:       (id: string) => `${v1}/requisition/${id}/approve`,
    STATUS:        (id: string) => `${v1}/requisition/${id}/status`,
    COST:          (id: string) => `${v1}/requisition/${id}/cost`,
    CONVERT_ASSET: (id: string) => `${v1}/requisition/${id}/convert-to-asset`,
  },
  LEAVE: {
    LIST:    `${v1}/timesheet/time-off`,
    APPROVE: (id: string) => `${v1}/timesheet/time-off/${id}/approve`,
    REJECT:  (id: string) => `${v1}/timesheet/time-off/${id}/reject`,
  },
  PERMISSION: {
    MY:                 `${v1}/permission/my-permissions`,
    DEFINITIONS:        `${v1}/permission/definitions`,
    MATRIX:             `${v1}/permission`,
    ROLE:               (roleName: string) => `${v1}/permission/${roleName}`,
    USER_OVERRIDES:     (userId: string) => `${v1}/permission/users/${userId}`,
    SET_USER_OVERRIDE:  (userId: string) => `${v1}/permission/users/${userId}`,
    DEL_USER_OVERRIDE:  (userId: string, permission: string) => `${v1}/permission/users/${userId}/${encodeURIComponent(permission)}`,
    DEL_ALL_OVERRIDES:  (userId: string) => `${v1}/permission/users/${userId}`,
    AUDIT_LOG:          `${v1}/permission/audit-log`,
    APPROVAL_RULES:     `${v1}/permission/approval-rules`,
    APPROVAL_RULE:      (id: string) => `${v1}/permission/approval-rules/${id}`,
    ROLES:              `${v1}/permission/roles`,
    ROLE_ENTITY:        (id: string) => `${v1}/permission/roles/${id}`,
    TEMPLATES:          `${v1}/permission/templates`,
    TEMPLATE:           (id: string) => `${v1}/permission/templates/${id}`,
    TEMPLATE_APPLY:     (id: string) => `${v1}/permission/templates/${id}/apply`,
    CATALOG:            `${v1}/permission/catalog`,
    CATALOG_ENTRY:      (id: string) => `${v1}/permission/catalog/${id}`,
  },
  DESKTOP: {
    LATEST_VERSION:  `${v1}/desktop/latest-version`,
    RELEASES:        `${v1}/desktop/releases`,
    RELEASE_ROLLOUT: (id: string) => `${v1}/desktop/releases/${id}/rollout`,
    RELEASE_DISABLE: (id: string) => `${v1}/desktop/releases/${id}/disable`,
    RELEASE_ROLLBACK: (id: string) => `${v1}/desktop/releases/${id}/rollback`,
    INSTALLATIONS:   `${v1}/desktop/installations`,
    FORCE_UPDATE:    (userId: string) => `${v1}/desktop/installations/${userId}/force-update`,
    ANALYTICS:       `${v1}/desktop/analytics`,
    RELEASE_TARGETS: (id: string) => `${v1}/desktop/releases/${id}/targets`,
    RELEASE_TARGET_DELETE: (id: string, targetId: string) => `${v1}/desktop/releases/${id}/targets/${targetId}`,
    CRASH_REPORTS:   `${v1}/desktop/crash-reports`,
    CRASH_REPORT_STATUS: (id: string) => `${v1}/desktop/crash-reports/${id}/status`,
  },
  CRM_WORKSPACE: {
    DASHBOARD:  `${v1}/crm/dashboard`,
    HIERARCHY:  `${v1}/crm/hierarchy`,
    SUPERVISOR: (userId: string) => `${v1}/crm/users/${userId}/supervisor`,
  },
  EMPLOYEE: {
    LIST:       `${v1}/employee`,
    STATS:      `${v1}/employee/stats`,
    DETAIL:     (id: string) => `${v1}/employee/${id}`,
  },
  EDUCATION: {
    LIST:   (userId: string) => `${v1}/education-record/${userId}`,
    CREATE: (userId: string) => `${v1}/education-record/${userId}`,
    UPDATE: (userId: string, id: string) => `${v1}/education-record/${userId}/${id}`,
    DELETE: (userId: string, id: string) => `${v1}/education-record/${userId}/${id}`,
  },
  EMPLOYMENT_HISTORY: {
    LIST:   (userId: string) => `${v1}/employment-history/${userId}`,
    CREATE: (userId: string) => `${v1}/employment-history/${userId}`,
    UPDATE: (userId: string, id: string) => `${v1}/employment-history/${userId}/${id}`,
    DELETE: (userId: string, id: string) => `${v1}/employment-history/${userId}/${id}`,
  },
  EMERGENCY_CONTACTS: {
    LIST:   (userId: string) => `${v1}/emergency-contacts/${userId}`,
    CREATE: (userId: string) => `${v1}/emergency-contacts/${userId}`,
    UPDATE: (id: string) => `${v1}/emergency-contacts/${id}`,
    DELETE: (id: string) => `${v1}/emergency-contacts/${id}`,
  },
  INCREMENT: {
    LIST:      `${v1}/increment`,
    CALCULATE: (userId: string) => `${v1}/increment/calculate/${userId}`,
    HISTORY:   (userId: string) => `${v1}/increment/${userId}/history`,
    CREATE:    (userId: string) => `${v1}/increment/${userId}`,
    UPDATE:    (userId: string, id: string) => `${v1}/increment/${userId}/${id}`,
    DELETE:    (userId: string, id: string) => `${v1}/increment/${userId}/${id}`,
  },
  OVERTIME: {
    LIST:    `${v1}/overtime`,
    STATS:   `${v1}/overtime/stats`,
    PAYROLL: `${v1}/overtime/payroll`,
    SUBMIT:  `${v1}/overtime`,
    DETAIL:  (id: string) => `${v1}/overtime/${id}`,
    APPROVE: (id: string) => `${v1}/overtime/${id}/approve`,
    REJECT:  (id: string) => `${v1}/overtime/${id}/reject`,
    CANCEL:  (id: string) => `${v1}/overtime/${id}/cancel`,
  },
  EXPENSES: {
    SUMMARY:      `${v1}/expenses/summary`,
    ACCOUNTS:     `${v1}/expenses/accounts`,
    ACCOUNT:      (userId: string) => `${v1}/expenses/accounts/${userId}`,
    TRANSACTIONS: (userId: string) => `${v1}/expenses/accounts/${userId}/transactions`,
    TRANSACTION:  (id: string)     => `${v1}/expenses/transactions/${id}`,
    RECEIPT:      (id: string)     => `${v1}/expenses/transactions/${id}/receipt`,
    CATEGORIES:   `${v1}/expenses/categories`,
  },
  DAILY_PLANNING: {
    MY_PROJECTS:    `${v1}/daily-planning/my-projects`,
    AGENDA:         `${v1}/daily-planning/agenda`,
    AGENDA_TODAY:   `${v1}/daily-planning/agenda/today`,
    AGENDA_FOR:     (userId: string, date: string) => `${v1}/daily-planning/agenda?user_id=${userId}&date=${date}`,
    REPORT:         `${v1}/daily-planning/report`,
    REPORT_TODAY:   `${v1}/daily-planning/report/today`,
    REPORT_FOR:     (userId: string, date: string) => `${v1}/daily-planning/report?user_id=${userId}&date=${date}`,
  },
  COMPLIANCE_VIOLATIONS: {
    LIST:   `${v1}/compliance/violations`,
    DETAIL: (id: string) => `${v1}/compliance/violations/${id}`,
  },
  HR_REPORT: {
    ANNUAL:    (userId: string) => `${v1}/hr-report/employee/${userId}/annual`,
    MONTHLY:   (userId: string) => `${v1}/hr-report/employee/${userId}/monthly`,
    AGGREGATE: `${v1}/hr-report/aggregate`,
    DASHBOARD_SUMMARY: `${v1}/hr-report/dashboard-summary`,
    MISSING_DOCUMENTS: `${v1}/hr-report/missing-documents`,
    MISSING_DOCUMENTS_SUMMARY: `${v1}/hr-report/missing-documents/summary`,
    MISSING_DOCUMENTS_EXPORT: `${v1}/hr-report/missing-documents/export`,
  },
  ANNOUNCEMENTS: {
    LIST:   `${v1}/announcements`,
    CREATE: `${v1}/announcements`,
    UPDATE: (id: string) => `${v1}/announcements/${id}`,
    DELETE: (id: string) => `${v1}/announcements/${id}`,
  },
  REPORTING: {
    PARSE:         `${v1}/reporting/parse`,
    INTERNAL_DATA: `${v1}/reporting/internal-data`,
    REPORTS:       `${v1}/reporting`,
    REPORT:        (id: string) => `${v1}/reporting/${id}`,
  },
  EMAIL_LOGS: `${v1}/email-logs`,
  MONITORING: {
    SCREENSHOTS:  `${v1}/monitoring/screenshots`,
    PRODUCTIVITY: `${v1}/monitoring/productivity`,
    APP_USAGE:    `${v1}/monitoring/app-usage`,
  },
  PAYROLL: {
    LIST:      `${v1}/payroll`,
    CREATE:    `${v1}/payroll`,
    GET:       (id: string) => `${v1}/payroll/${id}`,
    CALCULATE: (id: string) => `${v1}/payroll/${id}/calculate`,
    STATUS:    (id: string) => `${v1}/payroll/${id}/status`,
    PAYSLIP:   (runId: string, entryId: string) => `${v1}/payroll/${runId}/entries/${entryId}/payslip`,
    EMPLOYEE_PAYSLIPS: (userId: string) => `${v1}/payroll/employee/${userId}/payslips`,
  },
  CHAT: {
    USERS:       `${v1}/chat/users`,
    CHANNELS:    `${v1}/chat/channels`,
    CHANNEL:     (id: string) => `${v1}/chat/channels/${id}`,
    DM:          `${v1}/chat/channels/dm`,
    PRIVATE:     `${v1}/chat/channels/private`,
    JOIN:        (id: string) => `${v1}/chat/channels/${id}/join`,
    ARCHIVE:     (id: string) => `${v1}/chat/channels/${id}/archive`,
    LEAVE:       (id: string) => `${v1}/chat/channels/${id}/leave`,
    UNREAD_COUNT: `${v1}/chat/unread-count`,
    SEARCH:      `${v1}/chat/search`,
    MEMBERS:     (id: string) => `${v1}/chat/channels/${id}/members`,
    MEMBER:      (id: string, uid: string) => `${v1}/chat/channels/${id}/members/${uid}`,
    MEMBER_ROLE: (id: string, uid: string) => `${v1}/chat/channels/${id}/members/${uid}/role`,
    MESSAGES:    (id: string) => `${v1}/chat/channels/${id}/messages`,
    MESSAGE:     (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}`,
    THREAD:      (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}/thread`,
    REACTION:    (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}/reactions`,
    TYPING:      (id: string) => `${v1}/chat/channels/${id}/typing`,
    PIN:         (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}/pin`,
    PINNED:      (id: string) => `${v1}/chat/channels/${id}/pinned`,
    POLLS:       (id: string) => `${v1}/chat/channels/${id}/polls`,
    POLL_VOTE:   (id: string, pollId: string) => `${v1}/chat/channels/${id}/polls/${pollId}/vote`,
    POLL_CLOSE:  (id: string, pollId: string) => `${v1}/chat/channels/${id}/polls/${pollId}/close`,
    TASKS:       (id: string) => `${v1}/chat/channels/${id}/tasks`,
    REMINDERS:   (id: string) => `${v1}/chat/channels/${id}/reminders`,
    SAVE:        (id: string, msgId: string) => `${v1}/chat/channels/${id}/messages/${msgId}/save`,
    SAVED:       `${v1}/chat/saved`,
    EXPORT:      (id: string, format: string) => `${v1}/chat/channels/${id}/export?format=${format}`,
  },
  ZOOM_CHAT: {
    AUTHORIZE_URL: `${v1}/chat/zoom/authorize-url`,
    STATUS:        `${v1}/chat/zoom/status`,
    DISCONNECT:    `${v1}/chat/zoom/disconnect`,
    CONVERSATIONS: `${v1}/chat/zoom/conversations`,
    MESSAGES:      `${v1}/chat/zoom/messages`,
  },
  SERVERS: {
    LIST:        `${v1}/servers`,
    CREATE:      `${v1}/servers`,
    DETAIL:      (id: string) => `${v1}/servers/${id}`,
    CHANNELS:    (id: string) => `${v1}/servers/${id}/channels`,
    MEMBERS:     (id: string) => `${v1}/servers/${id}/members`,
    MEMBER:      (id: string, userId: string) => `${v1}/servers/${id}/members/${userId}`,
  },
  MEETING: {
    DASHBOARD:        `${v1}/meeting/dashboard`,
    LIST:             `${v1}/meeting`,
    CREATE:           `${v1}/meeting`,
    DETAIL:           (id: string) => `${v1}/meeting/${id}`,
    UPDATE:           (id: string) => `${v1}/meeting/${id}`,
    CLOSE:            (id: string) => `${v1}/meeting/${id}/close`,
    CANCEL:           (id: string) => `${v1}/meeting/${id}/cancel`,
    PARTICIPANTS:     (id: string) => `${v1}/meeting/${id}/participants`,
    TIMELINE:         (id: string) => `${v1}/meeting/${id}/timeline`,
    NOTES:            (id: string) => `${v1}/meeting/${id}/notes`,
    NOTE_UPDATE:      (noteId: string) => `${v1}/meeting/note/${noteId}`,
    DECISIONS:        (id: string) => `${v1}/meeting/${id}/decisions`,
    ACTION_ITEM_CREATE: (id: string) => `${v1}/meeting/${id}/action-item`,

    ROOM_LIST:        `${v1}/meeting/room`,
    ROOM_CREATE:      `${v1}/meeting/room`,
    ROOM_DETAIL:      (id: string) => `${v1}/meeting/room/${id}`,
    ROOM_UPDATE:      (id: string) => `${v1}/meeting/room/${id}`,
    ROOM_STATUS:      (id: string) => `${v1}/meeting/room/${id}/status`,
    ROOM_DELETE:      (id: string) => `${v1}/meeting/room/${id}`,
    ROOM_MEMBERS:     (id: string) => `${v1}/meeting/room/${id}/members`,
    ROOM_MEMBER:      (id: string, userId: string) => `${v1}/meeting/room/${id}/members/${userId}`,
    ROOM_TIMELINE:    (id: string) => `${v1}/meeting/room/${id}/timeline`,
    ROOM_AGENDA_LIST:   (id: string) => `${v1}/meeting/room/${id}/agenda`,
    ROOM_AGENDA_CREATE: (id: string) => `${v1}/meeting/room/${id}/agenda`,
    AGENDA_UPDATE:      (id: string, agendaId: string) => `${v1}/meeting/room/${id}/agenda/${agendaId}`,
    AGENDA_COMPLETE:    (id: string, agendaId: string) => `${v1}/meeting/room/${id}/agenda/${agendaId}/complete`,

    ACTION_ITEM_LIST:     `${v1}/meeting/action-item`,
    ACTION_ITEM_UPDATE:   (actionId: string) => `${v1}/meeting/action-item/${actionId}`,
    ACTION_ITEM_COMPLETE: (actionId: string) => `${v1}/meeting/action-item/${actionId}/complete`,

    ATTACHMENT_LIST:   `${v1}/meeting/attachment`,
    ATTACHMENT_CREATE: `${v1}/meeting/attachment`,
  },

  HR_DOCUMENTS: {
    PLACEHOLDERS:     `${v1}/hr-documents/placeholders`,

    CATEGORIES:       `${v1}/hr-documents/categories`,
    CATEGORY_UPDATE:  (id: string) => `${v1}/hr-documents/categories/${id}`,

    TYPES:            `${v1}/hr-documents/types`,
    TYPE_UPDATE:      (id: string) => `${v1}/hr-documents/types/${id}`,

    TEMPLATES:        `${v1}/hr-documents/templates`,
    TEMPLATE_DETAIL:  (id: string) => `${v1}/hr-documents/templates/${id}`,
    TEMPLATE_UPDATE:  (id: string) => `${v1}/hr-documents/templates/${id}`,
    TEMPLATE_VERSIONS:(id: string) => `${v1}/hr-documents/templates/${id}/versions`,
    TEMPLATE_DUPLICATE:(id: string) => `${v1}/hr-documents/templates/${id}/duplicate`,
    TEMPLATE_DELETE:  (id: string) => `${v1}/hr-documents/templates/${id}`,

    PREVIEW_RENDER:   `${v1}/hr-documents/render/preview`,

    LIST:             `${v1}/hr-documents`,
    DETAIL:           (id: string) => `${v1}/hr-documents/${id}`,
    GENERATE:         `${v1}/hr-documents/generate`,
    RENEW:            (id: string) => `${v1}/hr-documents/${id}/renew`,

    SEND:             (id: string) => `${v1}/hr-documents/${id}/send`,
    APPROVE_DRAFT:    (id: string) => `${v1}/hr-documents/${id}/approve-draft`,
    VIEW:             (id: string) => `${v1}/hr-documents/${id}/view`,
    REJECT:           (id: string) => `${v1}/hr-documents/${id}/reject`,
    CANCEL:           (id: string) => `${v1}/hr-documents/${id}/cancel`,
    ARCHIVE:          (id: string) => `${v1}/hr-documents/${id}/archive`,

    SIGN:             (id: string) => `${v1}/hr-documents/${id}/sign`,

    RESEND:           (id: string) => `${v1}/hr-documents/${id}/resend`,

    PDF:              (id: string) => `${v1}/hr-documents/${id}/pdf`,
    DOCX:             (id: string) => `${v1}/hr-documents/${id}/docx`,
  },

  HR_DOCUMENTS_PUBLIC: {
    DETAIL: (token: string) => `${v1}/public/hr-documents/${token}`,
    SIGN:   (token: string) => `${v1}/public/hr-documents/${token}/sign`,
  },

  ONBOARDING_OFFERS_PUBLIC: {
    DETAIL: (token: string) => `${v1}/public/onboarding/offers/${token}`,
    ACCEPT: (token: string) => `${v1}/public/onboarding/offers/${token}/accept`,
    REJECT: (token: string) => `${v1}/public/onboarding/offers/${token}/reject`,
  },

  EXECUTIVE_ANALYTICS: {
    DASHBOARD: `${v1}/executive-analytics/dashboard`,
  },

  INTERVIEWS: {
    LIST_FOR_CANDIDATE: (candidateId: string) => `${v1}/interviews/candidate/${candidateId}`,
    UPCOMING:           `${v1}/interviews/upcoming`,
    CREATE:             `${v1}/interviews`,
    UPDATE:             (id: string) => `${v1}/interviews/${id}`,
    DELETE:             (id: string) => `${v1}/interviews/${id}`,
    EMAIL_GENERATE:     (id: string) => `${v1}/interviews/${id}/email/generate`,
    EMAIL_EDIT:         (id: string) => `${v1}/interviews/${id}/email`,
    EMAIL_SEND:         (id: string) => `${v1}/interviews/${id}/email/send`,
  },

  OFFBOARDING: {
    TASKS:           (userId: string) => `${v1}/offboarding/tasks/${userId}`,
    CREATE_TASK:     `${v1}/offboarding/tasks`,
    COMPLETE_TASK:   (id: string) => `${v1}/offboarding/tasks/${id}/complete`,
    SET_TASK_STATUS: (id: string) => `${v1}/offboarding/tasks/${id}/status`,
    EXIT_DETAIL:     (userId: string) => `${v1}/offboarding/exit/${userId}`,
  },
  JOB_REQUISITIONS: {
    LIST:        `${v1}/job-requisitions`,
    CREATE:      `${v1}/job-requisitions`,
    DETAIL:      (id: string) => `${v1}/job-requisitions/${id}`,
    REVIEW:      (id: string) => `${v1}/job-requisitions/${id}/review`,
    STATUS:      (id: string) => `${v1}/job-requisitions/${id}/status`,
    CANCEL:      (id: string) => `${v1}/job-requisitions/${id}/cancel`,
    META:        `${v1}/job-requisitions/meta`,
  },
} as const;

export const NEW_ENDPOINTS = API_ENDPOINTS;

export const DOWNLOADS_ENDPOINTS = {
  LATEST: `${v1}/downloads/latest`,
  TRACK:  `${v1}/downloads/track`,
  STATS:  `${v1}/downloads/stats`,
} as const;
